### ISSUE TITLE
This specific code snipper will going to result in an error

### ISSUE THREAD

**Issue by nsonaniya2010** [rishuranjanofficial/JWTweak#1]
https://github.com/rishuranjanofficial/JWTweak/blob/28a4160f1cdd596241980f997104ef5eaaaad1c1/JWTweak.py#L54

```
                Header=part_jwt[0]
                if len(Header) % 4 != 0: #check if multiple of 4
                    while len(Header) % 4 != 0:
                        Header = Header + "="
                    req_str = base64.b64decode(Header)
                else:
                    req_str = base64.b64decode(Header)
                    str_req_str=req_str.decode('utf-8')
```
Due to Line #54 of code, and not the same line just before, this code will give an error when length of the header is not multiple of 4

Add  below line just before else condition.
```
str_req_str=req_str.decode('utf-8')
```

I can create a pull request if you want.

Thanks :)

**Comment by nsonaniya2010** [comment]
Same with the line:
https://github.com/rishuranjanofficial/JWTweak/blob/28a4160f1cdd596241980f997104ef5eaaaad1c1/JWTweak.py#L89

**Comment by rishuranjanofficial** [comment]
Thanks for the suggestion.
Please check and confirm what error we get for a valid JWT input and invalid JWT token. I will fix once you confirm. Thanks in advance.

**Comment by nsonaniya2010** [comment]
that snippet if you read, clearly shows that `str_req_str` is different than `req_str`.
Moreover if, 'if' condition is evaluated to be true (in case of token length not multiple of 4)  then `str_req_str` will never be set

**Comment by rishuranjanofficial** [comment]
Thanks for pointing out the issue. I haven't got the error for the valid JWT Token input with any supported algorithm. 

Still pushing the updated code in v1.1.1 with recommended code.

Hope you will use this tool for your bug hunting!

Let me know if you have any more suggestion. Post your confirmation, I will close this issue

**Comment by nsonaniya2010** [comment]
In the below valid token:

```
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImEiOiJiIn0.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.T7HfUYLLJ71JqWF47ZOMhAs_SUeI9JUQ39H8JWkougw
```
The header string contains 47 characters, which is not multiple of 4. You should get an error here (an exception will be catched here according to code.)

**Comment by rishuranjanofficial** [comment]
v1.1.1 is released with the suggested snippet. Closing this issue thread. Thanks once again.
