### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by xsuperbug** [rishuranjanofficial/JWTweak#3]
```
  File "JWTweak.py", line 26
    print(f"{bcolors.OKGREEN}\nThis is a valid input JWT Token{bcolors.ENDC}")
                                                                            ^
SyntaxError: invalid syntax

```

This way I get a lot of errors in python3.

**Comment by rishuranjanofficial** [comment]
Hi xsuperbug,

Which version of script you are using and what environment you are using for this script?

I am using kali linux for this. The script is working fine. 

Use this Command- **python3 JWTweak.py**

**Comment by rishuranjanofficial** [comment]
It seems that the above solution has resolved your issue. Closing this issue thread. However, you can comment if the issue still persists.
