### ISSUE TITLE
requirements.txt?

### ISSUE THREAD

**Issue by priyanshuxo** [rishuranjanofficial/JWTweak#4]

**Comment by priyanshuxo** [comment]
`Traceback (most recent call last):
  File "JWTweak.py", line 9, in <module>
    from Cryptodome.Signature import PKCS1_v1_5, DSS, pss
ModuleNotFoundError: No module named 'Cryptodome'`

Fixed the error by running pip install pycryptodomex

Include a requirements.txt file with pycryptodomex

**Comment by rishuranjanofficial** [comment]
Thanks for the suggestion.

Which version of script you are using and what environment you are using for this script?

I am using Kali Linux for this. The script is working fine using this Command- **python3 JWTweak.py**

**Comment by priyanshuxo** [comment]
I'm using the latest release and I'm on Ubuntu 20.04

**Comment by rishuranjanofficial** [comment]
I will take your suggestion in the next update roll out.

Hope you will use this tool for your bug hunting!

Let me know if you have any more suggestion or feedback.

**Comment by priyanshuxo** [comment]
Using it already pal! Closing this as of now.
